### ISSUE TITLE
Color errors in v10

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/Smart-Target#43]
```
smartTarget.js:217 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'color')
[Detected 2 packages: smarttarget, lib-wrapper]
    at Token5e._refreshTarget (smartTarget.js:217:26)
    at 🎁Token.prototype._refreshTarget#0 (libWrapper-wrapper.js:187:52)
    at Token5e._refresh (foundry.js:45426:10)
    at Token5e.refresh (foundry.js:24896:10)
    at Token5e.setTarget (foundry.js:46129:10)
    at TokenHUD._onToggleTarget (foundry.js:70578:11)
    at TokenHUD._onClickControl (foundry.js:70437:21)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```
This pops up when hovering a token.

```
smartTarget.js:217 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'color')
[Detected 2 packages: smarttarget, lib-wrapper]
    at Token5e._refreshTarget (smartTarget.js:217:26)
    at 🎁Token.prototype._refreshTarget#0 (libWrapper-wrapper.js:187:52)
    at Token5e._refresh (foundry.js:45426:10)
    at Token5e.refresh (foundry.js:24896:10)
    at Token5e._onHoverOut (foundry.js:25199:10)
    at Token5e._onHoverOut (foundry.js:46527:18)
    at MouseInteractionManager.callback (foundry.js:27466:45)
    at MouseInteractionManager._handleMouseOut (foundry.js:27605:17)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerOverOut (interaction.min.mjs:8:18331)
    at r.processPointerMove (interaction.min.mjs:8:17115)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
```
This pops up when hovering out.

Does it have something to do with it trying to set a color for the new default target indicator?

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/187909707-a03bc2fd-e66c-4fe0-bef2-5f2027822a82.png)
These are the settings, if it helps.

**Comment by theripper93** [comment]
fixed
